<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKDJyEHI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKDJyEHI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerKDJyEHI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerKDJyEHI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerKDJyEHI\appAppKernelProdContainer([
    'container.build_hash' => 'KDJyEHI',
    'container.build_id' => 'b8e102ce',
    'container.build_time' => 1697462755,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKDJyEHI');
